{% set name = "keras" %}
{% set version = "3.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-team/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cc23944e30a7159777cce52e6fa9d6c793607ffbc3cfc281dbd20791321a2558

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -v
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
  run:
    - python
    - absl-py
    - numpy
    - rich
    - namex >=0.0.8
    - h5py
    - optree
    - ml_dtypes
    - packaging
  run_constrained:
    # https://github.com/keras-team/keras/blob/v3.11.2/requirements.txt
    - tensorflow >=2.18.1,<2.19.0 # [py<313]
    - tensorflow-cpu >=2.18.1,<2.19.0  # [not osx and py<313]
    - pytorch ==2.6.0
    - torch-xla ==2.6.0  # [not osx]
    - jax ==0.5.0
    # https://github.com/keras-team/keras/blob/v3.11.2/requirements-common.txt
    - onnxscript <=0.3.1

test:
  script: run_test.py
  source_files:
    - pyproject.toml
    - integration_tests
    - keras
  requires:
    - pip
    # Temporary disabled till jax will be updated
    # - jax  # [not s390x]
    - tensorflow >=2.18.1,<2.19.0 # [py<313]
    - pytorch
    - pytest

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Deep Learning for humans
  description: |
    Keras 3 is a multi-backend deep learning framework, with support for JAX, 
    TensorFlow, and PyTorch. Effortlessly build and train models for computer 
    vision, natural language processing, audio processing, timeseries forecasting, 
    recommender systems, etc.
  doc_url: https://keras.io/
  dev_url: https://github.com/keras-team/keras

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - croth1
    - ocefpaf
    - jjhelmus
  skip-lints:
    # The imports section is moved down to the commands
    - missing_imports_or_run_test_py