{% set name = "Keras" %}
{% set version = "2.3.1" %}

#  NOTE: this recipe has problems with long paths on windows:
#  conda.CondaMultiError: The package for tensorflow-base located at C:\ci\containers\00000tc3o9d\tmp\build\80754af9\build_env\pkgs\tensorflow-base-2.1.0-eigen_py37h49b2757_0
# appears to be corrupted. The path 'Lib/site-packages/tensorflow-2.1.0.data/purelib/tensorflow_core/include/tensorflow_core/core/grappler/optimizers/generic_layout_optimizer_transposer_factory.h'
#
# You may need to build this manually so that you can have a shorter base path.
#
package:
  name: keras_split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 321d43772006a25a1d58eea17401ef2a34d388b588c9f7646c34796151ebc8cc

build:
  number: 0
  # skip platforms without tensorflow
  skip: True  # [win32 or linux32 or ppc64le or py>37]

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: keras-base
    script: install_base.sh  # [not win]
    script: install_base.bat # [win]
    build:
      # platforms/python versions without tensorflow support
      skip: True  # [win64 and py27]
    requirements:
      build:
        - python
        - pip
      run:
        - python
        - numpy >=1.9.1
        - scipy >=0.14
        - six >=1.9.0
        - pyyaml
        - h5py
        - keras-applications >=1.0.6
        - keras-preprocessing >=1.0.5
      # add run_constrained to prevent installation of mismatched keras and
      # keras-base packages
      run_constrained:
        - keras {{ version }}
    test:
      requires:
        - tensorflow
      imports:
        - keras
        - keras.backend
        - keras.datasets
        - keras.engine
        - keras.layers
        - keras.legacy
        - keras.preprocessing
        - keras.utils
        - keras.wrappers

  - name: keras
    requirements:
      run:
        - keras-base {{ version }}
        - tensorflow
    about:
      home: https://github.com/fchollet/keras
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Deep Learning Library for Theano and TensorFlow
      description: |
        Keras is a minimalist, highly modular neural networks library
        written in Python and capable on running on top of either
        TensorFlow or Theano. It was developed with a focus on enabling
        fast experimentation. Being able to go from idea to result with
        the least possible delay is key to doing good research.
      doc_url: http://keras.io
      dev_url: https://github.com/fchollet/keras

  - name: keras-gpu
    requirements:
      run:
        - keras-base {{ version }}
        - tensorflow-gpu
    about:
      home: https://github.com/fchollet/keras
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Deep Learning Library for Theano and TensorFlow
      description: |
        Keras is a minimalist, highly modular neural networks library
        written in Python and capable on running on top of either
        TensorFlow or Theano. It was developed with a focus on enabling
        fast experimentation. Being able to go from idea to result with
        the least possible delay is key to doing good research.
      doc_url: http://keras.io
      dev_url: https://github.com/fchollet/keras

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - croth1
    - ocefpaf
    - jjhelmus
