{% set version = "2.1.6" %}
{% set sha256 = "88734b83105a7f3aecfe52153db9f47cf7ab5a44c613922d43dc6d8b646f484e" %}

package:
    name: keras
    version: {{ version }}

source:
    url: https://github.com/fchollet/keras/archive/{{ version }}.tar.gz
    fn: keras-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - h5py
        - numpy >=1.9.1
        - setuptools
        - scipy >=0.14
        - tensorflow     # [not (win and py27)]
        - python
        - pyyaml
        - six >=1.9.0
        - theano         # [win and py27]

test:
    imports:
        - keras
        - keras.backend
        - keras.datasets
        - keras.engine
        - keras.layers
        - keras.preprocessing
        - keras.utils
        - keras.wrappers

about:
    home: https://github.com/fchollet/keras
    license: MIT
    summary: Deep Learning for Python

extra:
    recipe-maintainers:
        - ericdill
        - mariusvniekerk
        - croth1
