travis:
  secure:
    BINSTAR_TOKEN: qJpfLdBCjFup/IiULhCzdLxeKI+KIKFTDINwPpycvja+jCF7vKOv72r6245pbV2NIWr0AmEMsC37uU4CpE1gBuyHYd30o6DlBOOzMbZo6Dz2KRLZ9+atXXh8RzLWsS2RFgCHqzXE4UXoI6yRud5ZzBwGN25zQPvx7RAngqZssFc7OKHpwhCDTvLhxkxVheny7oxEyQxmPB7m2W5iUaFcQhcdToQj339G62hMmdDIFIGNSmSRij5XKup+xtpq619zhMOnvWGGlJEj0SSQQMFZ7uSbije4O97ybbHn/sgrHDshBHWbm0ZuawyB0DpqcFY+SQL/F6ASma80tZE+n8xnlggzldMiphTqJwgoMYKqQvaWJN00DLFqni+MqWxfLOjPbPYoLOrv1d/DEMb3gIbCV412S2R4K1A5yJXbbWd3CaGWU1BZXtFHvWgDtnXIogm4LLtqr+RC4y7NkHXLOKLMfYS+P7O1fnLxq0c14e1lrHPtVceiybMSRdPzRja0SHqui7mH9B/fTpSc0TDC7p84N6q3jbIny+7b6sWOUoeAPaejIY7izlcyPGWOQ2XFx3Ffx7o7BBgsNzhsJ10A54AHUGohZVhHDBPamCand6/TdP7KgodOFu3Nx53LqvWV8eoH7zH1KsaQS1ajvgQBLxcY4KufsuZw/r0YYcyMC6Nv2G8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
