travis:
  secure:
    BINSTAR_TOKEN: AtifPFbeNV5JD5cMUsDHNjsjLR1DySAqAx+GNOUqAQX5vVewPNypLkLk5QqfknFjno0dBAYbCCHYrgnroGEdHHwDu2j5tif45DduD1jjx5kihFldDQpV4f27lVDIyhoN6z09drqGdj8CWq6oJCr2bjh4Em5ZKOlZUK/s+9+GG7Rzu5WJfwqZ7f+dD6OiyGu+tyA5elW/NXLFMaKKuBvARxUauIu28O0RMv/FopQvzx0hv8HG1dKce+N8mRhUB0eLdvRUaTzDqiBxJldjFhn5hEB8IAwVe8gsUzANMW+VOvjSjShIsrMjg8bAiTA7loC3QQN+kbSnbnI+0bGfjrIgiDzuO7fyNsTmeyKOc69ya1XmLNq0aFo++18hX5gHw9Zha34sqMHsfXVE92Y51Inq/IUwqE+PL9NZD0jggIHAuGdV08DBmQyWBh38z4AqfRHKwByFN8kJOMlS2TogsfHxcFFlnUzQmBIiIKmY0B3DimWs9zrIgFYz3g5iZpivRBTw4LQ5RabRmNdDnbdoNKGcaOKfRFZmOdsn+ZWiavCfjxTSlMo6itTER8xybVtdZv5YbpVM650aNGTmR1bnE7lsZRdG1/QRCfnwEVywCRxB2SUg2xffG1yZJY77wD6vh7BlclVf26nehZXl0+28U8DSLvCJc539EceMLMNF5VJOmvM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
